# -*- coding: utf-8 -*-
"""Performance Predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1US_O8OGazPl_K06BAbkuzE6wlCzcm5h5
"""

!pip install gradio scikit-learn pandas numpy

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import gradio as gr

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('student_data.csv')

df = df.dropna()
X = df.drop('target', axis=1)
y = df['target']

X = pd.get_dummies(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def predict_student(hours_study, attendance, parental_education, internet_access, extracurricular, health, failures):
    input_dict = {
        'hours_study': hours_study,
        'attendance': attendance,
        'parental_education_' + parental_education: 1,
        'internet_access_' + internet_access: 1,
        'extracurricular_' + extracurricular: 1,
        'health': health,
        'failures': failures
    }
    for col in X.columns:
        if col not in input_dict:
            input_dict[col] = 0
    input_data = np.array([input_dict[col] for col in X.columns]).reshape(1, -1)
    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)
    return "🎓 Pass" if prediction[0] == 1 else "❌ Fail"

gr.Interface(
    fn=predict_student,
    inputs=[
        gr.Number(label="Hours of Study"),
        gr.Number(label="Attendance (%)"),
        gr.Radio(["high_school", "bachelor", "master"], label="Parental Education"),
        gr.Radio(["yes", "no"], label="Internet Access"),
        gr.Radio(["yes", "no"], label="Extracurricular Activities"),
        gr.Slider(1, 5, step=1, label="Health (1-5)"),
        gr.Slider(0, 3, step=1, label="Past Failures")
    ],
    outputs="text",
    title="📊 Student Performance Predictor",
    description="Enter student details to predict academic success."
).launch()